version: '3'
services:
  flask-ml:
    container_name: flask-ml
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: condaforge/mambaforge:22.9.0-1
    env_file:
      - ./docker/.env
    restart: always
    ports:
      - "5000:5000"
